add workspaces, failing test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,25 +5,44 @@ jobs:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
-      - run: echo "A first hello"
+      - run: mkdir -p my_workspace
+      - run: echo "A first hello" > my_workspace/echo-output
+      - persist_to_workspace:
+          root: my_workspace
+          paths:
+            - echo-output
+      
   test-unit:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
-      - checkout
-      - run: echo "A familiar hi"
+      - attach_workspace:
+          at: my_workspace
+      - run: cat my_workspace/echo-output
+      
   test-integration:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
-      - checkout
-      - run: echo "A cool wave"
+      - attach_workspace:
+          at: my_workspace
+      - run: |
+          # this will fail intentionally, we'll use SSH to debug and fix
+          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
+            echo "It worked!";
+          else
+            echo "Nope!"; exit 1
+          fi   
+
   deploy:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
-      - checkout
-      - run: echo "A final goodbye"
+      - attach_workspace:
+          at: my_workspace
+      - run: |
+          echo "Deploying!!!"
+          cat my_workspace_echo-output
 
 workflows:
   version: 2
